import type { Metadata } from "next";
import { Lora, Quicksand } from "next/font/google";
import "./globals.css";
import "locomotive-scroll/dist/locomotive-scroll.css";

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${quicksand.variable} font-quicksand`}>
        {children}
      </body>
    </html>
  );
}
